---
layout: cv
title: Ivan Ribeiro's CV
---

# Ivan Ribeiro  
Business Intelligence Analyst | Project Manager | Data Enthusiast

<div id="webaddress">
<a href="mailto:elivandsonribeiro@gmail.com">elivandsonribeiro@gmail.com</a>  
| <a href="https://www.linkedin.com/in/elivandsonribeiro/">LinkedIn Profile</a>  
</div>

## Currently

Student at BYU-Idaho and Assistant Project Manager at BYU-Idaho

### Specialized in

Data Analytics, BI Reporting, Project Management, Strategic Communication

### Tools & Skills

Power BI, SQL, Tableau, Excel, DAX, Trello  
Bilingual (Portuguese/English), Strategic Planning, Decision Making

## Education

`Jan 2025 - Jul 2026`  
__Brigham Young University - Idaho__  
Bachelor of Science in Business Analytics (GPA: 3.8)  
- Chief Networking Officer, Corporate Finance Society  
- 4-Year Merit Scholarship

## Experience

`Jan 2025 - Present`  
__BYU-Idaho__, Rexburg, ID  
*Assistant Project Manager*  
- Coordinated workflows and timelines for 10+ instructional design projects  
- Oversaw translation reviews across Business and Math courses  
- Reviewed and edited 250+ instructional math videos for clarity and alignment

`Oct 2024 - Dec 2024`  
__4Life Research__, Sandy, UT  
*Business Intelligence Analyst*  
- Designed Power BI dashboards for 15+ departments  
- Reduced reporting time by 30% using SQL automation  
- Improved dashboard accuracy by 25% with DAX

`Aug 2023 - Oct 2024`  
__BYU-Pathway__, Salt Lake City, UT  
*Assistant Project Manager*  
- Managed translation/localization of 6 academic programs in 3 languages  
- Used Tableau and Trello to coordinate 6 subcommittees

`Aug 2018 - Aug 2021`  
__4Life Research__, Sandy, UT  
*Business Analyst*  
- Increased affiliate qualifications by 60%  
- Trained and motivated 100+ consultants  
- Automated recurring reports and created Power BI dashboards

## Volunteer Experience

`Apr 2025 - Present`  
__BYU-Idaho – Corporate Finance Society__  
*Chief Networking Officer*  
- Built partnerships with 15+ guest speakers and 10+ companies  

## Awards

- 4-Year Merit Scholarship, BYU-Idaho

## Contact

- Email: [elivandsonribeiro@gmail.com](mailto:elivandsonribeiro@gmail.com)  
- LinkedIn: [linkedin.com/in/elivandsonribeiro](https://www.linkedin.com/in/elivandsonribeiro)
